CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# Battery monitoring
CONFIG_BT_BAS=y
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

CONFIG_ZMK_RGB_UNDERGLOW=y

CONFIG_ZMK_BATTERY_REPORTING_BLE=y
CONFIG_ZMK_BATTERY_REPORTING_USB=y
CONFIG_ZMK_BATTERY_REPORTING_SPLIT_FETCHING=y
CONFIG_ZMK_BATTERY_REPORTING_SPLIT_PROXY=y
CONFIG_ZMK_BATTERY_REPORTING_SPLIT_REPORT_LOWEST_CHARGE=n
